cart/urls.py
from django.urls import path

from .views import cart_detail_view, add_to_cart_view, remove_from_cart

app_name = 'cart'

urlpatterns = [
    path('', cart_detail_view, name='cart_detail'),
    path('add/<int:product_id>/', add_to_cart_view, name='add_to_cart'),
    path('remove/<int:product_id>/', remove_from_cart, name='remove_cart'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('allauth.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('orders.urls')),

    # Rosetta
    path('rosetta/', include('rosetta.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from .views import order_create_view

app_name = 'orders'

urlpatterns = [
    path('create/', order_create_view, name='order_create'),
]

cart/forms.py
from django import forms

class AddToCartProductForm(forms.Form):
    QUANTUTY_CHOICES = [(i, str(i)) for i in range(1,11)]

    quantity = forms.TypedChoiceField(choices=QUANTUTY_CHOICES, coerce=int)

    inplace = forms.BooleanField(required=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from products.models import Product
from .forms import AddToCartProductForm
from .cart import Cart


def cart_detail_view(request):
    cart = Cart(request)

    for item in cart:
        item['product_update_item_quantity_form'] = AddToCartProductForm(initial={
            'quantity': item['quantity'],
            'inplace': True,
        })

    return render(request, 'cart/cart_detail.html', context = {
        'cart': cart,
    })

@require_POST
def add_to_cart_view(request, product_id):
    cart = Cart(request)

    product = get_object_or_404(Product, id=product_id)
    form = AddToCartProductForm(request.POST)

    if form.is_valid():
        cleaned_data = form.cleaned_data
        quantity = cleaned_data['quantity']
        inplace = cleaned_data['inplace']
        cart.add(product, quantity, replace_current_quantity=inplace)

    return redirect('cart:cart_detail')

def remove_from_cart(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    cart.remove(product)

    return redirect('cart:cart_detail')

cart/templates/cart/cart_detail.html
{% extends '_base.html' %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load persian_translation_tags %}
{% load humanize %}

{% block page_title %}سبد خرید{% endblock page_title %}


{% block content %}

{% translate "Cart" as header_name %}
{% include 'title_header.html' with header_name=header_name %}

<!-- Main Content Wrapper Start -->
<div class="main-content-wrapper">
    <div class="page-content-inner ptb--80">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mb-md--50">
                        <div class="row no-gutters">
                            <div class="col-12">
                                {% if cart %}
                                    <div class="table-content table-responsive">
                                        <table class="table text-center">
                                            <thead>
                                                <tr>
                                                    <th>&nbsp;</th>
                                                    <th>{% trans "Product Image" %}</th>
                                                    <th>{% trans "Product Name" %}</th>
                                                    <th>{% trans "Price" %}</th>
                                                    <th>{% trans "Amount" %}</th>
                                                    <th>{% trans "total" %}</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for item in cart %}
                                                    <tr>
                                                        <td class="product-remove text-left">
                                                            <a href="{% url 'cart:remove_cart' item.product_obj.id %}">
                                                                <i class="flaticon flaticon-cross"></i>
                                                            </a>
                                                        </td>
                                                        <td class="product-thumbnail">
                                                            <img src="{{item.product_obj.image.url}}">
                                                        </td>
                                                        <td class="product-name">
                                                            <h3>
                                                                <a href="{{item.product_obj.get_absolute_url}}">
                                                                    {{item.product_obj.title}}
                                                                </a>
                                                            </h3>
                                                        </td>
                                                        <td class="product-price">
                                                            <span class="product-price-wrapper">
                                                                <span class="money">{{item.product_obj.price|intcomma:False|to_persian_numbers}} {% trans "Toman" %}</span>
                                                            </span>
                                                        </td>
                                                        <td class="product-quantity">
                                                            <form class="d-flex" method="POST" action="{% url 'cart:add_to_cart' item.product_obj.id %}">
                                                                {% csrf_token %}
                                                                <div class="quantity">
                                                                    <input 
                                                                        type="number"
                                                                        class="quantity-input"
                                                                        name="quantity" 
                                                                        id="qty-1" 
                                                                        value="{{item.quantity}}"
                                                                        min="1"
                                                                    >
                                                                </div>
                                                                {{ item.product_update_item_quantity_form.inplace }}
                                                                <button class="small" type="submit"><i class="fa fa-refresh"></i></button>
                                                            </form>
                                                        </td>
                                                        <td class="product-total-price">
                                                            <span class="product-price-wrapper">
                                                                <span class="money">{{item.total_price|intcomma:False|to_persian_numbers}} {% trans "Toman" %}</span>
                                                            </span>
                                                        </td>
                                                    </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                    <div class="row no-gutters border-top pt--20 mt--20">
                                        <div class="col-sm-6 text-sm-right">
                                            <button type="submit" class="cart-form__btn">خالی کردن سبد خرید</button>
                                        </div>
                                    </div>
                                    {% else %}
                                    <p>
                                        {% trans "Cart is Empty! Please Choose your product." %}
                                        <a href="{% url 'product_list' %}">
                                            {% trans "Go shopping" %}
                                        </a>
                                    </p>  
                                {% endif %}
                            </div>
                        </div>
                </div>
                <div class="col-lg-4">
                    <div class="cart-collaterals">
                        <div class="cart-totals">
                            <h5 class="font-size-14 font-bold mb--15">مجموع</h5>
                            <div class="cart-calculator">
                                <div class="cart-calculator__item order-total">
                                    <div class="cart-calculator__item--head">
                                        <span>{% trans "Total Price" %}</span>
                                    </div>
                                    <div class="cart-calculator__item--value">
                                        <span class="product-price-wrapper">
                                            <span class="money">{{cart.get_total_price|intcomma:False|to_persian_numbers}} {% trans "Toman" %}</span>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'orders:order_create' %}" class="btn btn-fullwidth btn-bg-red btn-color-white btn-hover-2">
                            ثبت سفارش
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Main Content Wrapper Start -->


{% endblock content %}

cart/templates/cart/cart_sidebar.html
{% load i18n %}

<!-- Mini Cart Start -->
<aside class="mini-cart" id="miniCart">
    <div class="mini-cart-wrapper">
        <a href="" class="btn-close"><i class="flaticon flaticon-cross"></i></a>
        <div class="mini-cart-inner">
            <h3 class="mini-cart__heading mb--40 mb-lg--30 text-right">{% trans "Cart" %}</h3>
            <div class="mini-cart__content">
                <ul class="mini-cart__list text-right">
                    {% for item in cart %}
                        <li class="mini-cart__product d-flex justify-content-between">
                            <div class="mini-cart__product__image">
                                <a href="#">
                                    <img src="assets/img/products/prod-1-100x100.jpg">
                                </a>
                            </div>
                            <div class="mini-cart__product__content pt-2">
                                <span class="mini-cart__product__title d-flex flex-row justify-content-between">
                                    <a href="{% url 'product_detail' item.product_obj.id %}">{{item.product_obj.title}}</a>
                                    <a href="{% url 'cart:remove_cart' item.product_obj.id %}" class="">
                                        &#10060;
                                    </a>
                                </span>
                                <span class="mini-cart__product__quantity">
                                    <span>{{item.product_obj.price}}</span> &#215; <span>{{item.quantity}}</span>
                                </span>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
                <div class="mini-cart__total">
                    <span>{% trans "Total Price" %}</span>
                    <span class="ammount">{{cart.get_total_price}} {% trans "Toman" %}</span>
                </div>
                <div class="mini-cart__buttons">
                    <a href="{% url 'cart:cart_detail' %}" class="btn btn-fullwidth btn-bg-sand mb--20">{% trans "View Cart" %}</a>
                    <a href="checkout.html" class="btn btn-fullwidth btn-bg-sand">{% trans "Payment" %}</a>
                </div>
            </div>
        </div>
    </div>
</aside>
<!-- Mini Cart End -->